# Configuración del linter

include: package:lint/analysis_options.yaml

# desactivo un par de features del lenguaje
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: false
    no_runtimeType_toString: false
    unrelated_type_equality_checks: false
    prefer_const_constructors: true
    avoid_classes_with_only_static_members: false
